### PR TITLE
Command-line version of the experiment scripts + log + tests

### PR DESCRIPTION
**Pull request by mgalardini**
Removed the GUI, now an experiment can be paused hitting Ctrl+C in the command line; hitting any key after that resumes the experiment, hitting Ctrl-C a second time stops it

Also added logging messages to a file, with an option to modulate verbosity, the name of the log file and an option to disable it entirely

Slightly refactored the custom_script.py file so that the users can pick the function relevant to them by just uncommenting a line

Also added a few command line options to make it easier to run from the command line

```
$ python3 main_eVOLVER.py -h
usage: main_eVOLVER.py [-h] [--always-yes] [--log-path LOG_PATH]
                       [--verbose | --quiet]

Run an eVOLVER experiment from the command line

optional arguments:
  -h, --help           show this help message and exit
  --always-yes         Answer yes to all questions (i.e. continues from
                       existing experiment, overwrites existing data and
                       blanks OD measurements)
  --log-path LOG_PATH  Path to the log file (default: evolver.log)
  --verbose            Increase logging verbosity level to DEBUG (default:
                       INFO)
  --quiet              Disable logging to file entirely
```

TODO: remove unused imports

### CODE REVIEW

**Comment by mgalardini** [comment]
ugh, just noticed #1, I will try to merge the two together

**Comment by mgalardini** [comment]
the `test_eVOLVER.py` script should allow users to test their `custom_script.py` files without actually have to run a toy experiment. potentially saves a lot of time and resources

**Comment by brandogw** [comment]
Seems like this is still based on the old version before Chris' PR. Sorry for being slow on on the PRs

**Comment by mgalardini** [comment]
No problem! I am probably gonna wait for Chris' last edits and then start from scratch to add these other changes. I'll probably open a new PR

**Pull request closed without merging**
